# aries:="./aries/aries/target/release/aries-plan-engine"    # Aries executable built in submodule [Standard parser, see `aries/README.md`]
# aries:="./aries/default-bin/standard/aries-plan-engine"    # Aries executable built in submodule [Standard parser, see `aries/README.md`]
aries:="./aries/default-bin/independent/aries-plan-engine"   # Aries executable built in submodule [Modified parser, see `aries/README.md` -- setting used in paper experiments]

aries_repair_mode:="smallest"

## -------------------
## HIGH-LEVEL COMMANDS
## -------------------

#### Figures

visualize_cactus_plots:
    ./src/visualize_cactus_plots.py output/aries/ground/summary.json output/baseline/ground/summary.json
    #./src/visualize_cactus_plots.py \
    #    output/aries/lifted/standard/033/summary.json output/aries/lifted/standard/066/summary.json output/aries/lifted/standard/100/summary.json \
    #    bavandpour/output/exhaust/033/summary.json bavandpour/output/exhaust/066/summary.json bavandpour/output/exhaust/100/summary.json \
    #    bavandpour/output/relaxpre/033/summary.json bavandpour/output/relaxpre/066/summary.json bavandpour/output/relaxpre/100/summary.json # standard
    ./src/visualize_cactus_plots.py \
        output/aries/lifted/independent/033/summary.json output/aries/lifted/independent/066/summary.json output/aries/lifted/independent/100/summary.json \
        output/baseline/lifted/exhaust/033/summary.json output/baseline/lifted/exhaust/066/summary.json output/baseline/lifted/exhaust/100/summary.json \
        output/baseline/lifted/relaxpre/033/summary.json output/baseline/lifted/relaxpre/066/summary.json output/baseline/lifted/relaxpre/100/summary.json # independent

visualize_scatter_plots:
    ./visualize_scatter_plots.py 60 baseline/output/ground/summary.json aries/output/ground/summary.json

#visualize_num_effects:
#    ./aries/visualize_num_effects.py aries/output/ground/summary.json aries_ground

#### Assert repair sizes

assert_repair_sizes:
    ./src/assert_repair_sizes.py output/aries/ground/summary.json output/baseline/ground/summary.json
    #./src/assert_repair_sizes.py output/aries/lifted/standard/033/summary.json output/baseline/lifted/exhaust/033/summary.json
    #./src/assert_repair_sizes.py output/aries/lifted/standard/066/summary.json output/baseline/lifted/exhaust/066/summary.json
    #./src/assert_repair_sizes.py output/aries/lifted/standard/100/summary.json output/baseline/lifted/exhaust/100/summary.json
    #./src/assert_repair_sizes.py output/aries/lifted/standard/033/summary.json output/baseline/lifted/relaxpre/033/summary.json
    #./src/assert_repair_sizes.py output/aries/lifted/standard/066/summary.json output/baseline/lifted/relaxpre/066/summary.json
    #./src/assert_repair_sizes.py output/aries/lifted/standard/100/summary.json output/baseline/lifted/relaxpre/100/summary.json
    ./src/assert_repair_sizes.py output/aries/lifted/independent/033/summary.json output/baseline/lifted/exhaust/033/summary.json
    ./src/assert_repair_sizes.py output/aries/lifted/independent/066/summary.json output/baseline/lifted/exhaust/066/summary.json
    ./src/assert_repair_sizes.py output/aries/lifted/independent/100/summary.json output/baseline/lifted/exhaust/100/summary.json
    ./src/assert_repair_sizes.py output/aries/lifted/independent/033/summary.json output/baseline/lifted/relaxpre/033/summary.json
    ./src/assert_repair_sizes.py output/aries/lifted/independent/066/summary.json output/baseline/lifted/relaxpre/066/summary.json
    ./src/assert_repair_sizes.py output/aries/lifted/independent/100/summary.json output/baseline/lifted/relaxpre/100/summary.json

#### Log parsing

parse_logs_all: 
    just parse_logs_ground
    just parse_logs_lifted_standard_033
    just parse_logs_lifted_standard_066
    just parse_logs_lifted_standard_100
    just parse_logs_lifted_independent_033
    just parse_logs_lifted_independent_066
    just parse_logs_lifted_independent_100

parse_logs_ground:
    #!/usr/bin/env bash
    logs_folder=output/aries/ground/logs
    output_file=output/aries/ground/summary.json
    just parse_logs "$logs_folder" aries_ground "$output_file"

parse_logs_lifted_standard_033:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/standard/033/logs
    output_file=output/aries/lifted/standard/033/summary.json
    just parse_logs "$logs_folder" aries_lifted_standard_033 "$output_file"

parse_logs_lifted_standard_066:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/standard/066/logs
    output_file=output/aries/lifted/standard/066/summary.json
    just parse_logs "$logs_folder" aries_lifted_standard_066 "$output_file"

parse_logs_lifted_standard_100:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/standard/100/logs
    output_file=output/aries/lifted/standard/100/summary.json
    just parse_logs "$logs_folder" aries_lifted_standard_100 "$output_file"

parse_logs_lifted_independent_033:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/independent/033/logs
    output_file=output/aries/lifted/independent/033/summary.json
    just parse_logs "$logs_folder" aries_lifted_independent_033 "$output_file"

parse_logs_lifted_independent_066:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/independent/066/logs
    output_file=output/aries/lifted/independent/066/summary.json
    just parse_logs "$logs_folder" aries_lifted_independent_066 "$output_file"

parse_logs_lifted_independent_100:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/independent/100/logs
    output_file=output/aries/lifted/independent/100/summary.json
    just parse_logs "$logs_folder" aries_lifted_independent_100 "$output_file"

#### Input preparation

prepare_benchmarks benchmarks_folder="../benchmarks/domrep/":
    just _prepare_benchmarks {{benchmarks_folder}} "1000000" "plans" ".plan" "input/aries/benchmarks_ground.txt"
    just _prepare_benchmarks {{benchmarks_folder}} "15" "lifted_plans/033" ".plan-lifted" "input/aries/benchmarks_lifted_033.txt"
    just _prepare_benchmarks {{benchmarks_folder}} "15" "lifted_plans/066" ".plan-lifted" "input/aries/benchmarks_lifted_066.txt"
    just _prepare_benchmarks {{benchmarks_folder}} "15" "lifted_plans/100" ".plan-lifted" "input/aries/benchmarks_lifted_100.txt"

#### Running experiments

## !!! NOTE: Please note that by default, the path to the logs folder hardcoded in the commands below contains the `independent` folder !!!
## !!!       Be sure to change it appropriately / suitably to your needs !!!

solve_all_local_ground:
    #!/usr/bin/env bash
    logs_folder=output/aries/ground/logs
    rm "$logs_folder/*"
    just solve_all_local 60 benchmarks_ground.txt "$logs_folder"

solve_all_local_lifted_033:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/independent/033/logs
    rm "$logs_folder/*"
    just solve_all_local 900 benchmarks_lifted_033.txt "$logs_folder"

solve_all_local_lifted_066:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/independent/066/logs
    rm "$logs_folder/*"
    just solve_all_local 900 benchmarks_lifted_066.txt "$logs_folder"

solve_all_local_lifted_100:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/independent/100/logs
    rm "$logs_folder/*"
    just solve_all_local 900 benchmarks_lifted_100.txt "$logs_folder"

solve_all_slurm_ground:
    #!/usr/bin/env bash
    logs_folder=output/aries/ground/logs
    rm "$logs_folder/*"
    just solve_all_slurm 60 benchmarks_ground.txt "$logs_folder"

solve_all_slurm_lifted_033:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/independent/033/logs
    rm "$logs_folder/*"
    just solve_all_slurm 900 benchmarks_lifted_033.txt "$logs_folder"

solve_all_slurm_lifted_066:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/independent/066/logs
    rm "$logs_folder/*"
    just solve_all_slurm 900 benchmarks_lifted_066.txt "$logs_folder"

solve_all_slurm_lifted_100:
    #!/usr/bin/env bash
    logs_folder=output/aries/lifted/independent/100/logs
    rm "$logs_folder/*"
    just solve_all_slurm 900 benchmarks_lifted_100.txt "$logs_folder"

## -------------------
## LOW-LEVEL COMMANDS
## -------------------

parse_logs logs_folder tag output="summary.json":
    ./src/parse_logs.py {{logs_folder}} {{tag}} > {{output}}

_prepare_benchmarks benchmarks_folder max_plan_length plans_subfolder_name plans_extension output_file:
    ./src/prepare_benchmarks.py {{benchmarks_folder}} {{max_plan_length}} {{plans_subfolder_name}} {{plans_extension}} > {{output_file}}

solve_all_local timeout benchmarks logs_folder="":
    #!/usr/bin/env bash
    set -euo pipefail
    cat {{benchmarks}} | while read -r domain_file problem_file plan_file; do
        if [ -z {{logs_folder}} ]; then
            just solve_one_local {{timeout}} "$plan_file" "$domain_file" "$problem_file"
        else
            domain_name=$(basename $(dirname "${domain_file}"))
            plan_name=$(basename "${plan_file%.*}")
            instance_id="${domain_name}__${plan_name}"
            output="{{logs_folder}}/aries-domrep-${instance_id}.log"
            just solve_one_local {{timeout}} "$plan_file" "$domain_file" "$problem_file" > "$output"
        fi
    done 

solve_all_slurm timeout benchmarks logs_folder:
    #!/usr/bin/env bash
    set -euo pipefail
    cat {{benchmarks}} | while read -r domain_file problem_file plan_file; do
        just solve_one_slurm {{logs_folder}} {{timeout}} "$plan_file" "$domain_file" "$problem_file"
    done 

solve_one_local timeout plan_file domain_file="" problem_file="":
    #!/usr/bin/env bash
    set -euo pipefail
    command="timeout {{timeout}} {{aries}} dom-repair --mode {{aries_repair_mode}} {{plan_file}}"

    if test "{{domain_file}}" && test "{{problem_file}}"; then
        command="${command} -p {{problem_file}} -d {{domain_file}}"
    elif test "{{problem_file}}"; then
        command="${command} -p {{problem_file}}"
    elif test "{{domain_file}}"; then
        command="${command} -d {{domain_file}}"
    else
        command="${command}" # If unspecified, Aries automatically finds the domain and problem paths
    fi

    ($command || echo "REPORT {{plan_file}}         TIMEOUT") #| grep REPORT

solve_one_slurm logs_folder timeout plan_file domain_file problem_file="":
    #!/usr/bin/env bash
    set -euo pipefail
    command="timeout {{timeout}} {{aries}} dom-repair --mode {{aries_repair_mode}} {{plan_file}} -d {{domain_file}}"

    if test "{{problem_file}}"; then
        command="$command -p {{problem_file}}"
    else
        command="$command" # If unspecified, Aries automatically finds the domain and problem paths
    fi

    domain_name=$(basename $(dirname {{domain_file}}))
    aux={{plan_file}}
    plan_name=$(basename "${aux%.*}")
    instance_id="${domain_name}__${plan_name}"

    job_name="aries-domrep-${instance_id}"
    output="{{logs_folder}}/job_%j_aries-domrep-${instance_id}.log"
    command="${command} || echo 'REPORT {{plan_file}}         TIMEOUT' "

    ./slurmshortcut.sh ${job_name} {{timeout}} "${output}" "${command}"
